version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    networks:
        - cinema-network
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
        SA_PASSWORD: "123@Passw0rd"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
    - cinema-network

  # cinema-usuarios:
  #   build:
  #       context: ../src/services/Cinema.Usuarios/Cinema.Usuario.Api
  #       dockerfile: Dockerfile
  #   ports:
  #       - "5000:5000"
  #   networks:
  #       - cinema-network

  # cinema-filmes:
  #   build:
  #       context: ../src/services/Cinema.Filmes
  #       dockerfile: Cinema.Filmes.Api/Dockerfile
  #   ports:
  #       - "5001:5001"
  #   networks:
  #       - cinema-network

  # cinema-bilhetes:
  #   build:
  #       context: ../src/services/Cinema.Bilhetes
  #       dockerfile: Cinema.Bilhetes.Api/Dockerfile
  #   ports:
  #       - "5002:5002"
  #   networks:
  #       - cinema-network

volumes:
  mongodb_data:
  sqlserver_data:

networks:
  cinema-network:
    driver: bridge
